name = "RTBJulia"
uuid = "04af9736-3fd9-43ce-b456-74816504871c"
authors = ["Andr√©s Morales"]
version = "1.0.0-DEV"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CoordinateTransformations = "0.6.4"
LinearAlgebra = "1.11.0"
Rotations = "1.7.1"
StaticArrays = "1.9.16"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
