name = "RTBJulia"
uuid = "f1ad3182-c6f5-4314-86c8-4bb61c60e07e"
authors = ["Andr√©s Morales"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
